version: "3.8"

services:
  api:
    image: ghcr.io/tinnghiaauto/admin-tinnghia-api:${ADMIN_TINNGHIA_API_TAG}
    container_name: admin_tinnghia_api
    env_file:
      - .env
    ports:
      - "7001:7001"
    restart: always

  web:
    image: ghcr.io/tinnghiaauto/admin-tinnghia-web:${ADMIN_TINNGHIA_WEB_TAG}
    container_name: admin_tinnghia_web
    ports:
      - "3001:80"
    restart: always
